# Generated by Django 5.1.1 on 2024-10-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted_answer',
        ),
        migrations.RemoveField(
            model_name='post',
            name='parent_post',
        ),
    ]
