# Generated by Django 5.1.1 on 2024-10-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='votes_count',
        ),
    ]
