version: '3.11'

services:
  redis:
    image: redis:7
    container_name: redis-stack
    ports:
      - "6379:6379"

  celery:
    build: .
    container_name: celery-worker
    command: ["celery", "-A", "stackoverflow", "worker", "-l", "INFO"]
    depends_on:
      - redis
      - web
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  web:
    build: .
    container_name: web-stack
    environment:
    # to check server running through docker or localhost
      - IS_DOCKER=true            
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "pip install -r requirements.txt &&
             python3 manage.py makemigrations &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
