global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: 'celery-flower'
    static_configs:
      - targets: ['celery-flower:5555']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
  
  - job_name: 'django'
    static_configs:
      - targets: ['web:9100']

      